# NATS
nats.host=localhost
nats.port=4222
nats.topic=fraud.check
nats.alertset.topic=alertset.store
nats.query.topic=fraud.query

# Redis
redis.host=localhost
redis.port=32768
redis.user=default
redis.password=redispw
redis.database=0

# App
app.thread.session.pool.size=100
app.processor.messaging.provider=ma.medtech.droolbuilder.messaging.SysoutMessageSender
app.processor.subject.parallelism.threshold=10
app.storage.clean.on.shutdown=true
app.wait.time=300000
app.processor.repository.class=ma.s2m.repository.PropertiesRepository
app.PropertiesRepository.load.from.classpath=false
app.PropertiesRepository.properties.file.path=C:\\Projets\\DTS\\MedTech@Work\\Innovation\\S2M\\Gestion de la fraude\\Source code\\fraudmanager\\config.properties

storage.type=eclipsestore
storage.memory.shard.count=4
storage.submit.timeout.ms=100
storage.flush.interval.ms=200
storage.config.file=C:\\Projets\\DTS\\MedTech@Work\\Innovation\\S2M\\Gestion de la fraude\\Source code\\fraudmanager\\config.properties
storage.path=C:\\Projets\\DTS\\MedTech@Work\\Innovation\\S2M\\Gestion de la fraude\\Source code\\fraudmanager\\storage_data
storage.default.node.name=node-0
storage.queue.size=100000
storage.disk.shard.count=1
storage.node-0.shards=0

node.name=node-0

fraudmanager.multinode=true
fraudmanager.default.node.name=node-0
fraudmanager.alertstoring.enabled=true

drools.rules.deployment.dir=C:\\Projets\\DTS\\MedTech@Work\\Innovation\\S2M\\Gestion de la fraude\\Source code\\FraudManager rules\\rules
drools.rules.agenda-group.ruletype.enabled=true
drools.debug.enabled=true
drools.profiler.enabled=true
drool.builder.repository.workspace.directory=C:\\Projets\\DTS\\MedTech@Work\\Innovation\\S2M\\Gestion de la fraude\\Source code\\FraudManager rules


router.wait.time=1000