# NATS
nats.host=localhost
nats.port=4222
nats.topic=fraud.check
# Redis
redis.host=localhost
redis.port=6379
redis.user=default
redis.password=redispw
redis.database=0

# App
app.thread.pool.size=30
app.queue.capacity=256
app.processor.messaging.provider=ma.medtech.droolbuilder.messaging.SysoutMessageSender
app.redis.clean.on.shutdown=true

drools.rules.deployment.dir=C:\\Projets\\DTS\\MedTech@Work\\Innovation\\S2M\\Gestion de la fraude\\Source code\\FraudManager rules\\rules
drools.rules.agenda-group.ruletype.enabled=true

drools.debug.enabled=false
drools.profiler.enabled=false
drool.builder.repository.workspace.directory=C:\\Projets\\DTS\\MedTech@Work\\Innovation\\S2M\\Gestion de la fraude\\Source code\\FraudManager rules

