# NATS
nats.host=localhost
nats.port=4222
nats.topic=fraud.check
# Redis
redis.host=localhost
redis.port=6379
redis.user=default
redis.password=redispw
redis.database=0

# App
app.thread.session.pool.size=100
app.processor.messaging.provider=ma.medtech.droolbuilder.messaging.SysoutMessageSender
app.processor.subject.parallelism.threshold=10
app.rocksdb.clean.on.shutdown=true
app.wait.time=300000

rocksdb.queue.size=30000
rocksdb.memory.shard.count=4
rocksdb.submit.timeout.ms=100
rocksdb.config.file=C:\\Projets\\DTS\\MedTech@Work\\Innovation\\S2M\\Gestion de la fraude\\Source code\\fraudmanager\\config.properties
rocksdb.default.node.name=node-1

nats.query.topic=fraud.query
fraudmanager.multinode=false

drools.rules.deployment.dir=C:\\Projets\\DTS\\MedTech@Work\\Innovation\\S2M\\Gestion de la fraude\\Source code\\FraudManager rules\\rules
drools.rules.agenda-group.ruletype.enabled=true

drools.debug.enabled=true
drools.profiler.enabled=true
drool.builder.repository.workspace.directory=C:\\Projets\\DTS\\MedTech@Work\\Innovation\\S2M\\Gestion de la fraude\\Source code\\FraudManager rules

rocksdb.path=C:\\Projets\\DTS\\MedTech@Work\\Innovation\\S2M\\Gestion de la fraude\\Source code\\fraudmanager\\rocksdb_data
rocksdb.queue.size=10000

