#app.processor.repository.class=ma.s2m.repository.PropertiesRepository
app.PropertiesRepository.load.from.classpath=true
#app.PropertiesRepository.properties.file.path=C:\\Projets\\DTS\\MedTech@Work\\Innovation\\S2M\\Gestion de la fraude\\Source code\\fraudmanager\\config.properties

app.processor.repository.class=ma.s2m.repository.ConfigServerRepository
app.ConfigServerRepository.config.server.url=http://localhost:8888
app.ConfigServerRepository.config.server.application=fraudmanagerConfigServer
app.ConfigServerRepository.config.server.profile=prod
app.ConfigServerRepository.config.server.label=master
app.ConfigServerRepository.config.server.username=asebban
app.ConfigServerRepository.config.server.password=@N4aF6CE6;p8(Dmm
app.ConfigServerRepository.config.server.failFast=true
app.ConfigServerRepository.config.server.connectTimeoutMs=5000
app.ConfigServerRepository.config.server.readTimeoutMs=5000